logging.level:
  com.slack.api: DEBUG
server:
  port: 3000

logging:
  level:
    org.springframework.web: ERROR
    com.mkyong: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss}[%thread]%-5level %logger{36} - %msg%n"

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://cognito-idp.${AWS_DEFAULT_REGION:ap-northeast-1}.amazonaws.com/${AWS_COGNITO_POOL_ID}/.well-known/jwks.json
      client:
        registration:
          cognito:
            clientId: ${AWS_COGNITO_CLIENT_ID}
            clientSecret: ${AWS_COGNITO_CLIENT_SECRET}
            scope: openid
            redirect-uri: http://localhost:8080/login/oauth2/code/cognito
            clientName: vuetoo3922d970_app_client
        provider:
          cognito:
            authorizarion-uri: https://kf.auth.${AWS_DEFAULT_REGION:ap-northeast-1}.amazoncognito.com/oauth2/authorize
            token-uri: https://kf.auth.${AWS_DEFAULT_REGION:ap-northeast-1}.amazoncognito.com/oauth2/token
            user-info-uri: https://kf.auth.${AWS_DEFAULT_REGION:ap-northeast-1}.amazoncognito.com/oauth2/userInfo
            user-info-authentication-method:
              - client_secret_basic
              - client_secret_post
            issuer-uri: https://cognito-idp.${AWS_DEFAULT_REGION:ap-northeast-1}.amazonaws.com/${AWS_COGNITO_POOL_ID}
            user-name-attribute: cognito:username

aws:
  region: ${AWS_DEFAULT_REGION:ap-northeast-1}
  dynamodb:
    timeRecord: time-record
    indenitity: user-identity
