package com.fukushi294.slack.infrastructure.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.EqualsAndHashCode;
import lombok.Setter;

import java.time.LocalDateTime;

@Setter
@EqualsAndHashCode
@DynamoDBTable(tableName = "TimeRecord")
public class TimeRecord {
    private String id;
    private String userId;
    private LocalDateTime startTime;
    private LocalDateTime endTime;

    public TimeRecord() {
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return this.id;
    }

    @DynamoDBAttribute
    public String getUserId() {
        return userId;
    }

    @DynamoDBAttribute
    public LocalDateTime getStartTime() {
        return startTime;
    }

    @DynamoDBAttribute
    public LocalDateTime getEndTime() {
        return endTime;
    }

}
